### ISSUE TITLE
Rose Pine Moon Feature Request

### ISSUE THREAD

**Issue by Derrekito** [rose-pine/discord#14]
I would love to have Rose Pine Moon added to the theme options. Cheers.

**Comment by mvllow** [comment]
I started to add `rose-pine-moon.theme.css` and noticed that our main theme has three values that are not in our current palette (perhaps an older version):

```css
.theme-dark {
  --background-primary: #393552;
  --background-secondary: #2a273f;
  --background-secondary-alt: #393552;
  --channeltextarea-background: #2c2842; /* TODO: Match palette*/
  --background-tertiary: #232136;
  --background-accent: #ebbcba;
  --text-normal: #dad7fd; /* TODO: Match palette */
  --text-spotify: #9ccfd8;
  --text-muted: #4f4c58 /* TODO: Match palette */;
  --text-link: #3e8fb0;
  --background-floating: #2a273f;
  --header-primary: #e0def4;
  --header-secondary: #9ccfd8;
  --header-spotify: #9ccfd8;
  --interactive-normal: #e0def4;
  --interactive-hover: #c4a7e7;
  --interactive-active: #e0def4;
  --ping: #eb6f92;
  --background-modifier-selected: #393552b4;
  --scrollbar-thin-thumb: #232136;
  --scrollbar-thin-track: transparent;
  --scrollbar-auto-thumb: #232136;
  --scrollbar-auto-track: transparent;
}
```

Aside from the commented colours, this code contains the updated palette values for moon. I don't have a way to test this personally but if someone wants to pick this up, feel free to start with the above :)
